### ISSUE TITLE
Mayacraftの追加要素に関して

### ISSUE THREAD

**Issue by haya58** [Pleurotus-eryngii/BountifulBlocksMod#10]
開発お疲れ様です。
テストプレイして感じたことなのですが，Mayacraftの追加要素がクリエイティブタブのあちこちに散らばってあまり分かりやすいとは言えない…気がするのでクリエイティブタブを追加しそこにまとめて追加はいかがでしょう。
もし手が離せないようでしたらこちらで実装しておきます。

**Comment by Pleurotus-eryngii** [comment]
そんなに時間がかかる処理でもないので実装しておきます。
ただ、基本一般公開向けではなくMinfoサバイバル企画向けであることをご理解いただきたいと思います。

**Comment by haya58** [comment]
@Pleurotus-eryngii 
そこは了解しておりますが，どうもデバッグがやりにくかったもので…お手数おかけします。
