### ISSUE TITLE
実績に関して

### ISSUE THREAD

**Issue by Pleurotus-eryngii** [Pleurotus-eryngii/BountifulBlocksMod#12]
開発お疲れ様です。

先日マージしていただいた実績追加ブランチですが、現段階では
奇妙な植物の入手･使用1･使用2
異様な植物の入手･使用1･使用2
が追加されています。
ただ、このままだと2本の線が並んでいるだけで味気なく、実績の意味合いも薄いですので、いくつか分岐する形で追加したいと思っています。

しかし、実装がしやすく理に適った実績が思いつかなかったため、案があれば伺いたいと思います。

「こういう要素を追加した上でこの実績を追加」という形でもかまいませんので、提案よろしくお願いいたします。

**Comment by haya58** [comment]
お疲れ様です。
とりあえず今思いついたことですが、それぞれの植物の使用までに更に幾つかの過程を設け（より現実に即した、乾燥・精製など）それらに対応した実績を実装する、というのはいかがでしょうか。
単なる実績の追加というよりは、mod全体を大きく改変することになりますので、ややお手間書けるかもしれませんが…

**Comment by Pleurotus-eryngii** [comment]
なるほど。乾燥に関しては精錬、抽出に関しては醸造台を使用する方向で適用してみようと思います。
貴重なご意見ありがたいです
