### ISSUE TITLE
GitHub Flow導入の提案

### ISSUE THREAD

**Issue by haya58** [Pleurotus-eryngii/BountifulBlocksMod#5]
@Pleurotus-eryngii 
提案という形で意見を述べさせていただきます。
先日私は「GitHub実践入門」という本を読んだのですが，その中で提案されていた開発フローの形として，「masterブランチはいつでもリリースできるような形にしておき，トピックブランチ(実装する機能ひとつにつきひとつのブランチ)を個別に作って完成したらmasterブランチにmergeする」というものがありました。
これを「GitHub Flow」というのですが**(Git flowではありません)**，この開発フローをこのMod開発に導入してみてはいかがでしょうか。
この説明だけでは分かりにくいかと思いますので，参考サイトを幾つか挙げさせていただきます。
- [GitHub Flow(Japan Translation)](https://gist.github.com/Gab-km/3705015) 
- [GitHub FlowでPull Requestベースな開発フローの進め方](http://qiita.com/harada4atsushi/items/527d5f98320d993b3072)
- [Github-flowを分かりやすく図解してみた](http://b.pyar.bz/blog/2014/01/22/github-flow/)

なにか質問等ありましたらお気軽にどうぞ。

**Comment by Pleurotus-eryngii** [comment]
丁寧な説明と提案ありがとうございます。ご紹介いただいたウェブページと説明などで概要は理解いたしました。

内容としてはとてもやりやすい方法かと思いますが、このMOD自体の更新部分がもうあまり残っていないため、今実装してもあまり役に立たない危険性があるかと思います。
何か大きな変更が複数ある場合は別ですが、ハーフブロックや階段の実装も没になりましたので・・・

はやぶささんがFlowのほうがやりやすい、という場合には私もその方向で進めますが、以上の1点に関しては考慮したほうがいいかと。

**Comment by haya58** [comment]
なるほど。
確かに実装する内容は残り少ないようですが，大きな変更がないということはその分低リスクで新しいシステムを試せるということにはならないでしょうか？
これから別のものを共同開発していく機会があったとき役に立つかと思いますし，ぜひ導入をおすすめしたいかと思います。

**Comment by Pleurotus-eryngii** [comment]
了解しました、masterは安定させてあるので今後の更新時に導入したいと思います。
