### ISSUE TITLE
developブランチに関して

### ISSUE THREAD

**Issue by haya58** [Pleurotus-eryngii/BountifulBlocksMod#8]
@Pleurotus-eryngii 
念のためお伺いしますが，現在リポジトリに紛れ込んでる(？)developブランチは特に必要ないかと思いますので，削除してもよろしいでしょうか？
なお，リモートで削除した状態でローカル環境でそれを反映させずpushしたりすると問題の原因になりますのでご注意を。

**Comment by Pleurotus-eryngii** [comment]
削除して問題ないかと思います。忠告ありがとうございます。
