### ISSUE TITLE
Github Flow導入後の雑感

### ISSUE THREAD

**Issue by haya58** [Pleurotus-eryngii/BountifulBlocksMod#9]
@Pleurotus-eryngii 
開発お疲れ様です。
GitHub Flowを導入して2つのPull requestをうまく実装することができました。突然の申し出にもかかわらず素早い対応ありがとうございました。
さて，今回GitHub Flowを扱ってみて，いくつか気づいたこと・改善してほしい部分がありましたので共有しておきたいと思います。
### トピックブランチの名前は原則小文字で
- また，単なる名詞形ではなくどんな実装をするのかわかるような名前（たとえば，「Poppytextureの追加」であれば「add-pappytexture」など）にしていただくようお願いします。
### コミット粒度をもう少し細かく
- 幾つかのクラスを変更した後コミットするとログがたどりにくくなってしまいますので，「1つのクラスを変更したら1コミット」と言った風に積み重ねていくとよいかと思います。

以上，ご確認いただければ幸いです。

**Comment by Pleurotus-eryngii** [comment]
了解いたしました、まだ不慣れな部分が多くご迷惑をおかけしてしまい申し訳ないです、留意します
